// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ProfileMicroservice.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20211020063323_FriendshipRequestTable")]
    partial class FriendshipRequestTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Friend", b =>
                {
                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FriendId");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            FriendId = new Guid("dcf7036a-ab3d-4d14-8276-8dcb1f5e2965"),
                            ProfileId = new Guid("07641816-9097-451e-8aef-9f24c5786c20")
                        },
                        new
                        {
                            FriendId = new Guid("ab2356a6-702a-4372-9554-7bdd6d111a30"),
                            ProfileId = new Guid("07641816-9097-451e-8aef-9f24c5786c20")
                        });
                });

            modelBuilder.Entity("Entities.Models.FriendshipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FriendshipRequests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec0b51f1-ed70-407c-b778-90bd968ebbda"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceverId = new Guid("dcf7036a-ab3d-4d14-8276-8dcb1f5e2965"),
                            SenderId = new Guid("ab2356a6-702a-4372-9554-7bdd6d111a30"),
                            Status = "Unread"
                        });
                });

            modelBuilder.Entity("Entities.Models.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Title = "Woman"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Title = "Man"
                        });
                });

            modelBuilder.Entity("Entities.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07641816-9097-451e-8aef-9f24c5786c20"),
                            AccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Age = 0,
                            FirstName = "asdasd",
                            GenderId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            ImageId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastName = "asdasd"
                        },
                        new
                        {
                            Id = new Guid("dcf7036a-ab3d-4d14-8276-8dcb1f5e2965"),
                            AccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Age = 0,
                            FirstName = "qweqwe",
                            GenderId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            ImageId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastName = "qweqwe"
                        },
                        new
                        {
                            Id = new Guid("ab2356a6-702a-4372-9554-7bdd6d111a30"),
                            AccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Age = 0,
                            FirstName = "dsfdsf",
                            GenderId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            ImageId = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastName = "dsfdsf"
                        });
                });

            modelBuilder.Entity("Entities.Models.Friend", b =>
                {
                    b.HasOne("Entities.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Entities.Models.Profile", b =>
                {
                    b.HasOne("Entities.Models.Gender", "Gender")
                        .WithMany("Profiles")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Entities.Models.Gender", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
